#!/bin/bash
# Auto-generated by Evan setup — regenerates auth-profiles.json from .secrets.env
# This runs before the clawdbot gateway starts to ensure auth is always configured.
set -e

SECRETS_FILE="/root/clawd-evan/.secrets.env"
AUTH_DIR="/root/.clawdbot/agents/main/agent"
AUTH_FILE="${AUTH_DIR}/auth-profiles.json"

if [ ! -f "$SECRETS_FILE" ]; then
  echo "[clawdbot-setup-auth] ERROR: $SECRETS_FILE not found" >&2
  exit 1
fi

source "$SECRETS_FILE"

if [ -z "$ANTHROPIC_API_KEY" ]; then
  echo "[clawdbot-setup-auth] ERROR: ANTHROPIC_API_KEY not set in $SECRETS_FILE" >&2
  exit 1
fi

mkdir -p "$AUTH_DIR"

cat > "$AUTH_FILE" << EOF
{
  "version": 1,
  "profiles": {
    "anthropic:manual": {
      "type": "api_key",
      "provider": "anthropic",
      "key": "${ANTHROPIC_API_KEY}"
    },
    "openai:manual": {
      "type": "api_key",
      "provider": "openai",
      "key": "${OPENAI_API_KEY}"
    }
  }
}
EOF

echo "[clawdbot-setup-auth] auth-profiles.json written OK"
